server:
  port: 3000

spring:
  # 데이터 베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}
  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update #pull 땡겼을 때 create 나오는 참사 가 발생할 수도 있음
  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true # 실제 배포하는 서버는 true
  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      static-locations: file:src/main/resources/static/
  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
      file-size-threshold: 30MB
# 파일 업로드 경로 설정
file:
  upload:
    path: D:/uploads
    url: /upload/
#로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace